#!/bin/bash

echo "🔍 AUDIT: Campaign 91 Generation Issues"
echo "========================================"
echo ""
echo "Issue: Still generating short videos (8s) and no sound"
echo "Campaign: https://ailldoit-staging-opcatz6zya-uc.a.run.app/campaign/91/generate"
echo ""
echo "📋 Step 1: Check Cloud Run Logs"
echo "--------------------------------"
echo "Run this command to see recent logs:"
echo ""
echo "gcloud run services logs read ailldoit-staging \\"
echo "  --region us-central1 \\"
echo "  --limit 500 \\"
echo "  | grep -E 'ROUTE DEBUG|Campaign Type|Generating|VIDEO PROCESSING|audio|Campaign ID.*91' \\"
echo "  | tail -100"
echo ""
echo "📋 Step 2: Check Campaign Type in Database"
echo "-------------------------------------------"
echo "The campaign might have:"
echo "  - campaignType = 'video' (old type)"
echo "  - campaignType = 'shortVideo' (wrong type)"
echo "  - campaignType = 'longVideo' (correct, but not working)"
echo ""
echo "Check with:"
echo "  SELECT id, name, campaign_type, brief FROM campaigns WHERE id = 91;"
echo ""
echo "📋 Step 3: Verify Deployment"
echo "----------------------------"
echo "Check if latest commit is deployed:"
echo ""
echo "gcloud run services describe ailldoit-staging \\"
echo "  --region us-central1 \\"
echo "  --format 'value(spec.template.spec.containers[0].image)'"
echo ""
echo "Latest commit should be: 49c8ffd (fix: Add audio track detection)"
echo ""
echo "📋 Step 4: Check What Should Happen"
echo "------------------------------------"
echo "Expected behavior:"
echo "  1. Log: 🔍 ROUTE DEBUG: Campaign Type: \"...\""
echo "  2. If type is 'video', log: ⚠️ ROUTE DEBUG: Campaign has old 'video' type..."
echo "  3. Log: 🔄 ROUTE DEBUG: Auto-updating campaign type..."
echo "  4. Log: 🎬 ROUTE: Generating long video for campaign type: longVideo"
echo "  5. Log: 🔊 VIDEO PROCESSING: Audio check results..."
echo ""
echo "If you see 'Generating short video' instead, the campaign type is wrong."
echo ""
echo "📋 Step 5: Quick Fix"
echo "-------------------"
echo "If campaign type is wrong, update it:"
echo ""
echo "  UPDATE campaigns SET campaign_type = 'longVideo' WHERE id = 91;"
echo ""
echo "Then regenerate the campaign."

